---
title: "Tentative Course Plan"
date: last-modified
author: "Austin Allen"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


::: {.panel-tabset}

### Fall 2023

#### Required

* BIOSTAT 701
* BIOSTAT 702
* BIOSTAT 703
* BIOSTAT 801

#### Top Considerations

* ECE 551D


#### Additional Courses

* STA 531
* BIOSTAT 823

#### Actual Courses Taken

* BIOSTAT 701
* BIOSTAT 702
* BIOSTAT 703
* BIOSTAT 801
* ECE 551D


### Spring 2024

#### Required

* BIOSTAT 705
* BIOSTAT 706
* BIOSTAT 802

#### Top Considerations

* BIOSTAT 704
* BIOSTAT 821


#### Additional Courses

* BIOSTAT 722
* BIOSTAT 709

#### Actual Courses Taken

* BIOSTAT 704 
* BIOSTAT 705
* BIOSTAT 706
* BIOSTAT 802
* BIOSTAT 821

### Fall 2024

#### Required

* BIOSTAT 720 (Master's Project)

#### Top Considerations

* BIOSTAT 707 (Statistical Methods for Learning and Discovery)
* BIOSTAT 719 (Generalized Linear Models)
* BIOSTAT 823 (Big Data Programming)

#### Additional Courses



* BIOSTAT 713 (Survival Analysis)
* BIOSTAT 724 (Introduction to Applied Bayesian Analysis)
* BIOSTAT 915 (High-Dimensional Statistics and Machine Learning)
* MATH 561 (Numerical Linear Algebra, Optimization and Monte Carlo Simulation)
* COMPSCI 671D (Theory and Algorithms for Machine Learning)




#### Actual Courses Taken



### Spring 2025

#### Required

* BIOSTAT 720 (Master's Project)

#### Top Considerations

* BIOSTAT 718 (Longitudinal and Correlated Data Analysis)
* BIOSTAT 724 (Introduction to Applied Bayesian Analysis)

#### Additional Courses

* BIOSTAT 709 (Observational Studies)
* BIOSTAT 824 (Case Studies in Biomedical Data Science)
* BME 590 (Special Topics in Biomedical Engineering, Spatial Omics with John Hickey)
* CBB 561 (Computational Sequence Biology)
* BIOSTAT 903 (Advanced Survival Analysis)
* SPANISH 204 (Advanced Intermediate Spanish-Audit Only)
* BIOLOGY 325 (Current Technologies in Genomics and Precision Medicine)
* BIOLOGY 417S (Genetic Engineering and Biotechnology)



#### Actual Courses Taken




:::